version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - gradle
    commit-message:
      prefix: "deps"
      include: scope
    groups:
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx:*"
      androidx:
        patterns:
          - "androidx.*"
      compose:
        patterns:
          - "androidx.compose.*"
      google-play:
        patterns:
          - "com.google.android.gms:*"
          - "com.google.firebase:*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
      include: scope
